"""followers

Revision ID: 209e93a56951
Revises: 776b0e9b4334
Create Date: 2021-01-11 11:02:13.120018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '209e93a56951'
down_revision = '776b0e9b4334'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
